### ISSUE TITLE
No output with external display

### ISSUE THREAD

**Issue by rdagger** [adafruit/Adafruit_CircuitPython_SSD1351#1]
I’m using the feather_nrf52840_express-en_US-4.0.0-beta.5.uf2. I’m trying to use the displayio library with an external SSD1351 OLED display.

The init sequence appears to work because I can manually control the display using SPI write commands.  However, none of the displayio commands appear to do anything.

Here's my test code based on the example here: https://github.com/adafruit/Adafruit_CircuitPython_ILI9341/blob/master/examples/ili9341_simpletest.py
```
import board
import displayio
from ssd1351dio import SSD1351
spi = board.SPI()
displayio.release_displays()
display_bus = displayio.FourWire(spi, command=board.D10,
                                 chip_select=board.D11, reset=board.D9)
display = SSD1351(display_bus)
splash = displayio.Group(max_size=10)
display.show(splash)
color_bitmap = displayio.Bitmap(128, 160, 1)
color_palette = displayio.Palette(1)
color_palette[0] = 0xFF0000
bg_sprite = displayio.TileGrid(color_bitmap, pixel_shader=color_palette, x=0, y=0)
splash.append(bg_sprite)
```

I also tried an external ST7735R LCD display and got nothing on the screen.

**Comment by makermelissa** [comment]
@rdagger, for the ST7735R display, I have a PR in that works with that display in the Adafruit_CircuitPython_ST7735 repo. If it's not merged by the time you see this, you can just grab it from my repo. Just run the `st7735_128x160_simpletest.py` example for that display and it should work. Also, the wiring on that hitletgo display is a little weird. Just follow the comments from the reviews for that display and make sure the LED + and - pins are connected to 3v and Ground respectively.

**Comment by rdagger** [comment]
@makermelissa Your awesome!  Downloaded the code from your repo and it just worked.

**Comment by rdagger** [comment]
@makermelissa I'm reviewing your code now to see where I went wrong.  I'm a bit confused by the following:
```
_INIT_R2_RED = (
    b"\x2a\x00\x00\x00\x7F" # _CASET XSTART = 0, XEND = 127
    b"\x2b\x00\x00\x00\x9F" # _RASET XSTART = 0, XEND = 159
)

_INIT_R2_GREEN_144 = (
    b"\x2a\x00\x00\x00\x7F" # _CASET XSTART = 0, XEND = 127
    b"\x2b\x00\x00\x00\x7F" # _RASET XSTART = 0, XEND = 127
)

_INIT_R2_GREEN_160X80 = (
    b"\x2a\x00\x00\x00\x4F" # _CASET XSTART = 0, XEND = 79
    b"\x2b\x00\x00\x00\x9F" # _RASET XSTART = 0, XEND = 159
)
It was my understanding that the second hex byte determined the delay and the byte length?
```

**Comment by rdagger** [comment]
Also according to my data sheet display inversion is 0x20 (off) and 0x21 (on).  Why are using 0x2A?
`b"\x2a\x00" # _INVOFF`

**Comment by rdagger** [comment]
The colors were off on my display.  I modifed the _INOFF and it's now correct:
`b"\x21\x00" # _INVOFF`

**Comment by makermelissa** [comment]
Hi @rdagger, IIRC, it looks like after the command (first byte), the second byte determines if a delay occurs if it is >= 0x80. However, that may be only for certain commands. I read it just enough to get this stuff working. 

However, regarding the sizing, I'll probably strip that out. According to Scott that's not needed.

Regarding the INVOFF, according to the datasheet you are correct. That's part of the original file I was modifying and you may have found a bug there. Thanks.

Most likely we will be having only 2 classes of ST7735 and some additional calls may be necessary after it is initialized for certain boards depending on whether it is an RGB or BGR display.

Since you got your display functioning, I'm going to close this issue.

**Comment by rdagger** [comment]
I was able to switch the display from BGR to RGB by modifying d3 bit of MADCTL:
```
_INIT_R4_BLACK = (
    b"\x36\x01\xC8" # _MADCTL Rotate to Landscape Mode
)
```

**Comment by makermelissa** [comment]
Yep, that's how I did it too.

**Comment by rdagger** [comment]
Thanks, I really appreciate all your help.
