### ISSUE TITLE
Set Column & Set Row command data bytes are 16bit (8bit needed)

### ISSUE THREAD

**Issue by rdagger** [adafruit/Adafruit_CircuitPython_SSD1351#2]
I took another look at the SSD1351 driver with my scope.  I confirmed the init sequence is working by manual sending SPI commands to the display using the _FourWire.send()_ method.  The following code draws a blue vertical line on the display at column 10:
```
x=10
color = 20
line = color.to_bytes(2, 'big') * 384
display_bus.send(0x15, (x << 8 | x).to_bytes(2, 'big'))
display_bus.send(0x75, b"\x00\x7F")
display_bus.send(0x5C, line)
```
I then used a scope to compare my working SPI commands with the non-working commands sent by displayio.  The SSD1351 set_column (0x15) and set_row command (0x75) expects 2 bytes for start and end address.  However, displayio is sending 4 bytes.
![Scope SPI Compare01](https://user-images.githubusercontent.com/106355/54871164-643cf000-4d6d-11e9-9ac0-748148813912.jpg)

**Comment by makermelissa** [comment]
Good find. This sounds like a it would be an enhancement for displayio. You could file it under https://github.com/adafruit/circuitpython/issues

I'm not sure how good at c you are (you seem great at protocols), but maybe you could even add the enhancement yourself and submit a PR. :)

**Comment by makermelissa** [comment]
Looks like the change would need to be made at: https://github.com/adafruit/circuitpython/blob/fce63b17c6051072c05b6d77c6c0ae0811d6bafc/shared-module/displayio/Display.c#L213

**Comment by makermelissa** [comment]
Also, you would probably need to add a way to specify the bytes for each command (most likely in the constructor) defaulting to 2 byte parameters.

**Comment by rdagger** [comment]
I posted the [issue](https://github.com/adafruit/circuitpython/issues/1683) to the main CircuitPython repo.  It looks like an easy fix but I think I’ll let someone else code it.  I’d like to contribute but I’ll have to study up on how to set up the environment and toolchain to build CircuitPython.  I’m currently doing all my hobby work on a Raspberry Pi.  

Thanks again for all the help and great advice.

**Comment by makermelissa** [comment]
You're welcome. I might take a stab it myself. :)
